#pragma once

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE  140
#define RGB_MATRIX_DEFAULT_SAT  244
#define RGB_MATRIX_DEFAULT_VAL  255
#define RGB_MATRIX_DEFAULT_SPD  0
#define OLED_DISPLAY_128X64
